language: cpp
dist: xenial

compiler:
  - clang

os:
  - linux

script:
  - make && make run_main && make run_test 
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code
