language: cpp
compiler:
  - clang 
  - gcc


os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code