language: cpp
compiler: gcc


os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - make  
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - export CXX=clang++-6.0
  - export CXX=g++-8
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
