sudo: false
language: cpp
compiler:
  - gcc
  - clang
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - gcc-7
    - g++-7
    - clang
    - cmake

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
